name: Create Pull Request
on:
  push:
    branches:
      - main
env:
  GITHUB_TOKEN: ${{ secrets.TEST_SECRET_TOKEN }}

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.7.0
        with:
          token: ${{ secrets.PARENT_REPO_TOKEN}}
          commit-message: Automated PR creation
          title: New Pull Request
          body: This is a new pull request created by the GitHub Action.
          branch: my-branch
          base: main
          repository: 14Richa/parentRepo1

