name: Comment on Pull Request
on:
  pull_request:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.TEST_SECRET_TOKEN }}
          script: |
            const welcomeMessage = "Thanks for opening this pull request!";
            const { owner, repo } = context.repo;
            const { number: issue_number } = context.issue;
            return github.issues.createComment({ owner, repo, issue_number, body: welcomeMessage });
