name: Auto-merge pull request

on:
  pull_request:
    types: [opened, reopened]

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check if pull request author is owner
        if: github.event.pull_request.user.login == github.repository_owner
        run: |
          echo "Pull request opened by owner."
          curl -XPUT \
            -H "Authorization: token ${{ secrets.TEST_SECRET_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"merge_method":"squash"}' \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge"
