# PRINT IT ON PR ITSELF 
name: Welcome New Contributor
on:
  push: 
    branches: 
      -main

  pull_request:
    branches: 
      - main
    paths:
      - 'config/**'
jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
        # parentRepo1 repo clone
      - name: Checkout parentRepo1 
        uses: actions/checkout@v3
        with:
          repository: 14Richa/parentRepo1
          path: parentRepo1
      - name: Compare files
        script: |
          const fs = require("fs");
          const origMembers = JSON.parse(fs.readFileSync("parentRepo1/config/TSC_MEMBER.json"));
          const newMembers = JSON.parse(fs.readFileSync("config/TSC_MEMBER.json"));
          console.log("FILE1", file1);
          console.log("FILE2", file2);

          const added = newMembers.filter(
            (newObj) => !origMembers.some((oldObj) => oldObj.name === newObj.name)
          );
          const removed = origMembers.filter(
            (oldObj) => !newMembers.some((newObj) => newObj.name === oldObj.name)
          );
          if(added.length > 0) return ::set-output name=diff::true;
          if(removed.length > 0) return ::set-output name=diff::false;

          console.log("Added objects:", added);
          console.log("Removed objects:", removed);
      - name: Display welcome message
        if: ${{ steps.compare-files.outputs.added == 'true' }}
        run: echo "Welcome!"
      - name: Display goodbye message
        if: ${{ steps.compare-files.outputs.removed == 'true' }}
        run: echo "Welcome!"


