# PRINT IT ON PR ITSELF 
name: Welcome New Contributor
on:
  push: 
    branches: 
      -main

  pull_request:
    branches: 
      - main
    paths:
      - 'config/**'
jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
        # parentRepo1 repo clone
      - name: Checkout parentRepo1 
        uses: actions/checkout@v3
        with:
          repository: 14Richa/parentRepo1
          path: parentRepo1
      - name: Compare files
          run: |
            differences=$(jq -s '.[0] - .[1] | {name: .name}' config/TSC_MEMBER.json parentRepo1/config/TSC_MEMBER.json)
            if [ -n "$differences" ]; then
              echo "The following changes were made"
              echo "$differences"
            fi

