# PRINT IT ON PR ITSELF 
name: Welcome New Contributor
on:
  push: 
    branches: 
      -main

  pull_request:
    branches: 
      - main
    paths:
      - 'config/**'
jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
        # parentRepo1 repo clone
      - name: Checkout parentRepo1 
        uses: actions/checkout@v3
        with:
          repository: 14Richa/parentRepo1
          path: parentRepo1
      - name: Compare files
        id: compare-files
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require("fs");
            const origMembers = JSON.parse(fs.readFileSync("parentRepo1/config/TSC_MEMBER.json"));
            const newMembers = JSON.parse(fs.readFileSync("config/TSC_MEMBER.json"));
            console.log("FILE1", origMembers);
            console.log("FILE2", newMembers);
  
            const added = newMembers.filter(
              (newObj) => !origMembers.some((oldObj) => oldObj.name === newObj.name)
            );
            const removed = origMembers.filter(
              (oldObj) => !newMembers.some((newObj) => newObj.name === oldObj.name)
            );
            if(added.length > 0)  console.log(`::set-output name=added::true`);
            if(removed.length > 0) console.log(`::set-output name=removed::true`);
            console.log("Added objects:", added);
            console.log("Removed objects:", removed);
      - name: Print Values
        run: |
          echo ${{steps.compare-files.outputs.added}}
          echo ${{steps.compare-files.outputs.removed}}

      - name: Display welcome message
        if: ${{ steps.compare-files.outputs.added == 'true' }}
        runs-on: ubuntu-latest
        steps:
          - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.TEST_SECRET_TOKEN}}
          script: |
            const welcomeMessage = `Welcome to AsyncAPI. Thanks a lot for reporting your first issue. Please check out our [contributors guide](https://github.com/asyncapi/community/blob/master/CONTRIBUTING.md) and the instructions about a [basic recommended setup](https://github.com/asyncapi/community/blob/master/git-workflow.md) useful for opening a pull request.<br />Keep in mind there are also other channels you can use to interact with AsyncAPI community.`;
            const { owner, repo } = context.repo;
            const { number: issue_number } = context.issue;
            return github.issues.createComment({ owner, repo, issue_number, body: welcomeMessage });


