# PRINT IT ON PR ITSELF 
name: Welcome New Contributor
on:
  pull_request:
    types: [closed, opened]
    paths:
      - 'TSC_MEMBERS.json' 

jobs:
  welcome:
    # if: github.event.pull_request.merged && github.event.pull_request.user.login != github.event.repository.owner.login
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # parentRepo1 repo clone
      - name: Checkout parentRepo1 
        uses: actions/checkout@v3
        with:
          repository: 14Richa/parentRepo1
          path: parentRepo1
      - name: Run script
        run: | 
          ls 
          cat parentRepo1/config/TSC_MEMBERS.json

       


