# name: ci-tests
## when to run this actions ... 
# on:
#   push:
#     branches:
#       - main
#       - 'release/**'
#   pull_request:
#     types:
#       - opened
#       - reopened
#       - synchronize
#       - ready_for_review
#     branches:
#       - main
#       - 'release/**'
#   schedule:
#     - cron: "0 */2 * * *" # every 2hrs

## what to do (tasks)
# jobs:
#   tests:
#     runs-on: ubuntu-20.04
#     steps:
#       - uses: actions/checkout@v3
#       - name: Print Hello World
#         run: |
#           echo "Hello world"
#       - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
#         uses: GuillaumeFalourd/clone-github-repo-action@v2
#         with:
#           owner: '14Richa'
#           repository: 'comic-strip_react'
#       - name: Show directories
#         run: |
#           cd comic-strip_react && ls
#           # workflow to close the pr
#       - name: Close Pull Request
#         run: | 
#           echo " PR Closed."

name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-20.4
    steps:
      - id: automerge
        name: automerge
        uses: "testga/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
