name: Check PR Merge Status

on:
  pull_request:
    types: [closed]

jobs:
  check_merge_status:
    runs-on: ubuntu-20.4
    steps:
      - name: Check if PR was merged
        if: github.event.pull_request.merged == true
        run: echo "Welcome"
