name: Send message to new member
on:
  pull_request:
    types: [closed]
  push:
    branches:
      - main
jobs: 
  tests: 
    runs-on: ubuntu-latest
    steps:
      - name: Check if new member
        uses: actions/github-script@v3
        with:
          script: |
            const contributors = await github.repos.listContributors({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const prAuthor = context.payload.pull_request.user.login;
            const isMember = contributors.data.some(c => c.login === prAuthor);
            core.setOutput('isMember', isMember);
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Send message to new member
        if: steps.check_if_new_member.outputs.isMember == 'true' && github.event.pull_request.merged == true
        uses: actions/github-script@v3
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const message = 'Congratulations on your first merged Pull Request! Thanks for your contribution.';
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: message,
            });
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}