# name: Send message to new member
# on:
#   pull_request:
#     types: [closed]
#   push:
#     branches:
#       - main
# jobs: 
#   tests: 
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check if new member
#         uses: actions/github-script@v3
#         with:
#           script: |
#             const contributors = await github.repos.listContributors({
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#             });
#             const prAuthor = context.payload.pull_request.user.login;
#             const isMember = contributors.data.some(c => c.login === prAuthor);
#             core.setOutput('isMember', isMember);
#           env:
#             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       - name: Send message to new member
#         if: steps.check_if_new_member.outputs.isMember == 'true' && github.event.pull_request.merged == true
#         uses: actions/github-script@v3
#         with:
#           script: |
#             const prNumber = context.payload.pull_request.number;
#             const message = 'Congratulations on your first merged Pull Request! Thanks for your contribution.';
#             await github.issues.createComment({
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               issue_number: prNumber,
#               body: message,
#             });
#           env:
#             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

### PRINT IT ON BASH

# name: Welcome New Contributor
# on:
#   pull_request:
#     types: [closed]
# jobs:
#   welcome:
#     if: github.event.pull_request.merged && github.event.pull_request.user.login != github.event.repository.owner.login
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Print welcome message
#         run: |
#           echo "Welcome to our project, @${{ github.event.pull_request.user.login }}! Thank you for your contribution."


# PRINT IT ON PR ITSELF 

name: Welcome New Contributor

on:
  pull_request:
    types: [closed]

jobs:
  welcome:
    if: github.event.pull_request.merged && github.event.pull_request.user.login != github.event.repository.owner.login
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Comment on Pull Request
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Welcome to our project, @' + context.payload.pull_request.user.login + '! Thank you for your contribution.'
            });
